name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main  
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.APP_PUBLISH_PROFILE }}
  WEBAPP_NAME: "WalahirElec"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: npm install, build, and test FrontEnd
        run: |
          cd client
          npm install
          npm run build
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone

      - name: Install backend dependencies
        run : |
          cd server
          npm install

    #   - name: "Deploy to Azure Web App"
    #     id: deploy-to-webapp
    #     uses: azure/webapps-deploy@v3
    #     with:
    #       app-name: ${{ env.WEBAPP_NAME }}
    #       slot-name: "Production"
    #       publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
    #       package: ./client/build/standalone

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}